apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-data-loading
  namespace: {{ NAMESPACE }}
  labels:
    name: es-data-loading
    component: elasticsearch-loading
    role: data
spec:
  selector:
    matchLabels:
      component: elasticsearch-loading
      role: data
  serviceName: es-data-loading
  replicas: {{ ES_DATA_NUM_PODS }}
  template:
    metadata:
      labels:
        name: es-data-loading
        deployment: {{ DEPLOY_TO }}
        component: elasticsearch-loading
        role: data
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - data
              topologyKey: kubernetes.io/hostname
      containers:
      - name: es-data-loading
        image: quay.io/pires/docker-elasticsearch-kubernetes:{{ ELASTICSEARCH_VERSION }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: "{{ ES_CLUSTER_NAME }}"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms{{ ELASTICSEARCH_JVM_MEMORY }} -Xmx{{ ELASTICSEARCH_JVM_MEMORY }}"
        - name: ES_PLUGINS_INSTALL
          value: "repository-gcs"  # ,mapper-size
        - name: SHARD_ALLOCATION_AWARENESS_ATTR
          value: "/etc/hostname"
        - name: SHARD_ALLOCATION_AWARENESS
          value: "data_node_hostname"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
        - name: storage
          mountPath: /data
      nodeSelector:
        cloud.google.com/gke-nodepool: "loading-cluster"
        cloud.google.com/gke-local-ssd: "true"
      volumes:
        - name: "storage"
          hostPath:
            path: "/mnt/disks/ssd0"