kind: ConfigMap
apiVersion: v1
metadata:
  name: es-kibana-config
  namespace: {{ NAMESPACE }}
  labels:
    component: es-kibana
data:
  kibana.yml: |
    ---
    server.name: es-kibana
    server.host: "0.0.0.0"
    elasticsearch.url: http://elasticsearch:9200
---
kind: Service
apiVersion: v1
metadata:
  name: es-kibana
  namespace: {{ NAMESPACE }}
  labels:
    component: es-kibana
spec:
  #type: NodePort
  selector:
    component: es-kibana
  ports:
  - name: es-kibana
    port: {{ KIBANA_SERVICE_PORT }}
    #nodePort: 30002
    #targetPort: http
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: es-kibana
  namespace: {{ NAMESPACE }}
  labels:
    component: es-kibana
    name: es-kibana
    deployment: {{ DEPLOY_TO }}
spec:
  replicas: 1
  selector:
    matchLabels:
     component: es-kibana
  template:
    metadata:
      labels:
        component: es-kibana
        name: es-kibana
        deployment: {{ DEPLOY_TO }}
    spec:
      containers:
      - name: es-kibana
        image: docker.elastic.co/kibana/kibana-oss:{{ ELASTICSEARCH_VERSION }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        env:
        - name: CLUSTER_NAME
          value: {{ ES_CLUSTER_NAME }}
        #- name: SERVER_BASEPATH
        #  value: /api/v1/namespaces/{{ NAMESPACE }}/services/es-kibana:{{ KIBANA_SERVICE_PORT }}/proxy
        resources:
          requests:
            cpu: 0.01
          limits:
            cpu: 1
        ports:
        - containerPort: {{ KIBANA_SERVICE_PORT }}
          protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /usr/share/kibana/config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: es-kibana-config