# Generated by Django 2.2.5 on 2019-10-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('colon', 'colon'), ('nerve', 'nerve'), ('small_intestine', 'small_intestine'), ('brain', 'brain'), ('whole_blood', 'whole_blood'), ('adipose_tissue', 'adipose_tissue'), ('vagina', 'vagina'), ('thyroid', 'thyroid'), ('lung', 'lung'), ('breast', 'breast'), ('spleen', 'spleen'), ('kidney', 'kidney'), ('heart', 'heart'), ('liver', 'liver'), ('blood_vessel', 'blood_vessel'), ('prostate', 'prostate'), ('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('muscle', 'muscle'), ('testis', 'testis'), ('uterus', 'uterus'), ('ovary', 'ovary'), ('adrenal_gland', 'adrenal_gland'), ('pancreas', 'pancreas'), ('esophagus', 'esophagus'), ('pituitary', 'pituitary'), ('skin', 'skin'), ('salivary_gland', 'salivary_gland'), ('stomach', 'stomach')], max_length=40),
        ),
    ]
