# Generated by Django 2.2.5 on 2019-10-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0002_auto_20191001_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('liver', 'liver'), ('blood_vessel', 'blood_vessel'), ('spleen', 'spleen'), ('thyroid', 'thyroid'), ('prostate', 'prostate'), ('testis', 'testis'), ('lung', 'lung'), ('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('adipose_tissue', 'adipose_tissue'), ('heart', 'heart'), ('pancreas', 'pancreas'), ('pituitary', 'pituitary'), ('esophagus', 'esophagus'), ('ovary', 'ovary'), ('whole_blood', 'whole_blood'), ('vagina', 'vagina'), ('breast', 'breast'), ('uterus', 'uterus'), ('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('brain', 'brain'), ('adrenal_gland', 'adrenal_gland'), ('small_intestine', 'small_intestine'), ('salivary_gland', 'salivary_gland'), ('colon', 'colon'), ('muscle', 'muscle'), ('kidney', 'kidney'), ('nerve', 'nerve'), ('skin', 'skin'), ('stomach', 'stomach')], max_length=40),
        ),
    ]
