# Generated by Django 2.2.5 on 2019-10-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0003_auto_20191001_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('liver', 'liver'), ('pituitary', 'pituitary'), ('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('uterus', 'uterus'), ('blood_vessel', 'blood_vessel'), ('salivary_gland', 'salivary_gland'), ('lung', 'lung'), ('testis', 'testis'), ('muscle', 'muscle'), ('breast', 'breast'), ('kidney', 'kidney'), ('adipose_tissue', 'adipose_tissue'), ('spleen', 'spleen'), ('vagina', 'vagina'), ('small_intestine', 'small_intestine'), ('heart', 'heart'), ('adrenal_gland', 'adrenal_gland'), ('pancreas', 'pancreas'), ('nerve', 'nerve'), ('prostate', 'prostate'), ('esophagus', 'esophagus'), ('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('whole_blood', 'whole_blood'), ('stomach', 'stomach'), ('brain', 'brain'), ('ovary', 'ovary'), ('thyroid', 'thyroid'), ('colon', 'colon'), ('skin', 'skin')], max_length=40),
        ),
    ]
