# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-09 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0017_auto_20190909_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('whole_blood', 'whole_blood'), ('thyroid', 'thyroid'), ('kidney', 'kidney'), ('esophagus', 'esophagus'), ('ovary', 'ovary'), ('salivary_gland', 'salivary_gland'), ('colon', 'colon'), ('lung', 'lung'), ('prostate', 'prostate'), ('muscle', 'muscle'), ('skin', 'skin'), ('nerve', 'nerve'), ('vagina', 'vagina'), ('adipose_tissue', 'adipose_tissue'), ('liver', 'liver'), ('brain', 'brain'), ('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('stomach', 'stomach'), ('adrenal_gland', 'adrenal_gland'), ('breast', 'breast'), ('heart', 'heart'), ('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('spleen', 'spleen'), ('uterus', 'uterus'), ('blood_vessel', 'blood_vessel'), ('pituitary', 'pituitary'), ('testis', 'testis'), ('small_intestine', 'small_intestine'), ('pancreas', 'pancreas')], max_length=40),
        ),
    ]
