# Generated by Django 2.2 on 2019-09-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0020_auto_20190909_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('adrenal_gland', 'adrenal_gland'), ('salivary_gland', 'salivary_gland'), ('kidney', 'kidney'), ('uterus', 'uterus'), ('esophagus', 'esophagus'), ('testis', 'testis'), ('colon', 'colon'), ('blood_vessel', 'blood_vessel'), ('prostate', 'prostate'), ('vagina', 'vagina'), ('pituitary', 'pituitary'), ('breast', 'breast'), ('pancreas', 'pancreas'), ('spleen', 'spleen'), ('thyroid', 'thyroid'), ('whole_blood', 'whole_blood'), ('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('muscle', 'muscle'), ('ovary', 'ovary'), ('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('skin', 'skin'), ('nerve', 'nerve'), ('brain', 'brain'), ('lung', 'lung'), ('heart', 'heart'), ('stomach', 'stomach'), ('adipose_tissue', 'adipose_tissue'), ('small_intestine', 'small_intestine'), ('liver', 'liver')], max_length=40),
        ),
    ]
