# Generated by Django 2.2 on 2019-09-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0022_auto_20190909_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('blood_vessel', 'blood_vessel'), ('salivary_gland', 'salivary_gland'), ('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('ovary', 'ovary'), ('muscle', 'muscle'), ('thyroid', 'thyroid'), ('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('nerve', 'nerve'), ('adrenal_gland', 'adrenal_gland'), ('kidney', 'kidney'), ('heart', 'heart'), ('prostate', 'prostate'), ('whole_blood', 'whole_blood'), ('brain', 'brain'), ('vagina', 'vagina'), ('skin', 'skin'), ('liver', 'liver'), ('pituitary', 'pituitary'), ('esophagus', 'esophagus'), ('spleen', 'spleen'), ('colon', 'colon'), ('lung', 'lung'), ('stomach', 'stomach'), ('pancreas', 'pancreas'), ('breast', 'breast'), ('testis', 'testis'), ('adipose_tissue', 'adipose_tissue'), ('small_intestine', 'small_intestine'), ('uterus', 'uterus')], max_length=40),
        ),
    ]
