# Generated by Django 2.2 on 2019-09-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0023_auto_20190909_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('prostate', 'prostate'), ('muscle', 'muscle'), ('nerve', 'nerve'), ('breast', 'breast'), ('heart', 'heart'), ('testis', 'testis'), ('blood_vessel', 'blood_vessel'), ('pancreas', 'pancreas'), ('small_intestine', 'small_intestine'), ('salivary_gland', 'salivary_gland'), ('adrenal_gland', 'adrenal_gland'), ('whole_blood', 'whole_blood'), ('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('pituitary', 'pituitary'), ('spleen', 'spleen'), ('stomach', 'stomach'), ('esophagus', 'esophagus'), ('colon', 'colon'), ('vagina', 'vagina'), ('thyroid', 'thyroid'), ('ovary', 'ovary'), ('liver', 'liver'), ('lung', 'lung'), ('kidney', 'kidney'), ('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('adipose_tissue', 'adipose_tissue'), ('brain', 'brain'), ('uterus', 'uterus'), ('skin', 'skin')], max_length=40),
        ),
    ]
