# Generated by Django 2.2 on 2019-09-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0025_auto_20190909_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('lung', 'lung'), ('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('adipose_tissue', 'adipose_tissue'), ('brain', 'brain'), ('ovary', 'ovary'), ('pituitary', 'pituitary'), ('adrenal_gland', 'adrenal_gland'), ('nerve', 'nerve'), ('muscle', 'muscle'), ('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('blood_vessel', 'blood_vessel'), ('skin', 'skin'), ('esophagus', 'esophagus'), ('breast', 'breast'), ('spleen', 'spleen'), ('small_intestine', 'small_intestine'), ('uterus', 'uterus'), ('kidney', 'kidney'), ('whole_blood', 'whole_blood'), ('stomach', 'stomach'), ('heart', 'heart'), ('vagina', 'vagina'), ('salivary_gland', 'salivary_gland'), ('pancreas', 'pancreas'), ('testis', 'testis'), ('colon', 'colon'), ('liver', 'liver'), ('prostate', 'prostate'), ('thyroid', 'thyroid')], max_length=40),
        ),
    ]
