# Generated by Django 2.2 on 2019-09-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0026_auto_20190909_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('breast', 'breast'), ('esophagus', 'esophagus'), ('heart', 'heart'), ('pancreas', 'pancreas'), ('liver', 'liver'), ('ovary', 'ovary'), ('brain', 'brain'), ('pituitary', 'pituitary'), ('lung', 'lung'), ('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('muscle', 'muscle'), ('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('salivary_gland', 'salivary_gland'), ('stomach', 'stomach'), ('uterus', 'uterus'), ('adipose_tissue', 'adipose_tissue'), ('thyroid', 'thyroid'), ('adrenal_gland', 'adrenal_gland'), ('spleen', 'spleen'), ('blood_vessel', 'blood_vessel'), ('small_intestine', 'small_intestine'), ('nerve', 'nerve'), ('whole_blood', 'whole_blood'), ('kidney', 'kidney'), ('colon', 'colon'), ('prostate', 'prostate'), ('vagina', 'vagina'), ('skin', 'skin'), ('testis', 'testis')], max_length=40),
        ),
    ]
