# Generated by Django 2.2 on 2019-09-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0027_auto_20190909_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('stomach', 'stomach'), ('salivary_gland', 'salivary_gland'), ('pancreas', 'pancreas'), ('uterus', 'uterus'), ('lung', 'lung'), ('adipose_tissue', 'adipose_tissue'), ('prostate', 'prostate'), ('vagina', 'vagina'), ('thyroid', 'thyroid'), ('kidney', 'kidney'), ('testis', 'testis'), ('adrenal_gland', 'adrenal_gland'), ('colon', 'colon'), ('brain', 'brain'), ('nerve', 'nerve'), ('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('breast', 'breast'), ('small_intestine', 'small_intestine'), ('esophagus', 'esophagus'), ('ovary', 'ovary'), ('liver', 'liver'), ('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('whole_blood', 'whole_blood'), ('muscle', 'muscle'), ('skin', 'skin'), ('blood_vessel', 'blood_vessel'), ('spleen', 'spleen'), ('pituitary', 'pituitary'), ('heart', 'heart')], max_length=40),
        ),
    ]
