# Generated by Django 2.2 on 2019-09-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0030_auto_20190909_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('brain', 'brain'), ('testis', 'testis'), ('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('pituitary', 'pituitary'), ('nerve', 'nerve'), ('prostate', 'prostate'), ('adrenal_gland', 'adrenal_gland'), ('kidney', 'kidney'), ('small_intestine', 'small_intestine'), ('colon', 'colon'), ('skin', 'skin'), ('thyroid', 'thyroid'), ('ovary', 'ovary'), ('vagina', 'vagina'), ('adipose_tissue', 'adipose_tissue'), ('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('muscle', 'muscle'), ('uterus', 'uterus'), ('breast', 'breast'), ('heart', 'heart'), ('liver', 'liver'), ('salivary_gland', 'salivary_gland'), ('esophagus', 'esophagus'), ('pancreas', 'pancreas'), ('blood_vessel', 'blood_vessel'), ('whole_blood', 'whole_blood'), ('lung', 'lung'), ('stomach', 'stomach'), ('spleen', 'spleen')], max_length=40),
        ),
    ]
