# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-09 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0015_auto_20190625_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('heart', 'heart'), ('thyroid', 'thyroid'), ('esophagus', 'esophagus'), ('muscle', 'muscle'), ('whole_blood', 'whole_blood'), ('adipose_tissue', 'adipose_tissue'), ('testis', 'testis'), ('stomach', 'stomach'), ('salivary_gland', 'salivary_gland'), ('prostate', 'prostate'), ('pituitary', 'pituitary'), ('brain', 'brain'), ('uterus', 'uterus'), ('kidney', 'kidney'), ('adrenal_gland', 'adrenal_gland'), ('ovary', 'ovary'), ('small_intestine', 'small_intestine'), ('vagina', 'vagina'), ('lung', 'lung'), ('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('blood_vessel', 'blood_vessel'), ('liver', 'liver'), ('skin', 'skin'), ('breast', 'breast'), ('nerve', 'nerve'), ('pancreas', 'pancreas'), ('spleen', 'spleen'), ('colon', 'colon')], max_length=40),
        ),
        migrations.AlterField(
            model_name='omim',
            name='phenotype_map_method',
            field=models.CharField(blank=True, choices=[('1', 'the disorder is placed on the map based on its association with a gene, but the underlying defect is not known.'), ('2', 'the disorder has been placed on the map by linkage; no mutation has been found.'), ('3', 'the molecular basis for the disorder is known; a mutation has been found in the gene.'), ('4', 'a contiguous gene deletion or duplication syndrome, multiple genes are deleted or duplicated causing the phenotype.')], max_length=1, null=True),
        ),
    ]
