# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-09 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0016_auto_20190909_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('liver', 'liver'), ('salivary_gland', 'salivary_gland'), ('small_intestine', 'small_intestine'), ('colon', 'colon'), ('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('lung', 'lung'), ('prostate', 'prostate'), ('adrenal_gland', 'adrenal_gland'), ('blood_vessel', 'blood_vessel'), ('breast', 'breast'), ('pituitary', 'pituitary'), ('heart', 'heart'), ('muscle', 'muscle'), ('brain', 'brain'), ('skin', 'skin'), ('kidney', 'kidney'), ('thyroid', 'thyroid'), ('ovary', 'ovary'), ('esophagus', 'esophagus'), ('adipose_tissue', 'adipose_tissue'), ('spleen', 'spleen'), ('whole_blood', 'whole_blood'), ('vagina', 'vagina'), ('stomach', 'stomach'), ('pancreas', 'pancreas'), ('nerve', 'nerve'), ('uterus', 'uterus'), ('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('testis', 'testis')], max_length=40),
        ),
    ]
