# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-09 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0018_auto_20190909_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('whole_blood', 'whole_blood'), ('testis', 'testis'), ('blood_vessel', 'blood_vessel'), ('muscle', 'muscle'), ('liver', 'liver'), ('small_intestine', 'small_intestine'), ('spleen', 'spleen'), ('lung', 'lung'), ('vagina', 'vagina'), ('esophagus', 'esophagus'), ('ovary', 'ovary'), ('colon', 'colon'), ('adrenal_gland', 'adrenal_gland'), ('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('brain', 'brain'), ('kidney', 'kidney'), ('pancreas', 'pancreas'), ('breast', 'breast'), ('stomach', 'stomach'), ('nerve', 'nerve'), ('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('heart', 'heart'), ('adipose_tissue', 'adipose_tissue'), ('uterus', 'uterus'), ('skin', 'skin'), ('salivary_gland', 'salivary_gland'), ('pituitary', 'pituitary'), ('thyroid', 'thyroid'), ('prostate', 'prostate')], max_length=40),
        ),
    ]
