# Generated by Django 2.2 on 2019-09-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0019_auto_20190909_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('uterus', 'uterus'), ('whole_blood', 'whole_blood'), ('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('colon', 'colon'), ('liver', 'liver'), ('vagina', 'vagina'), ('muscle', 'muscle'), ('blood_vessel', 'blood_vessel'), ('salivary_gland', 'salivary_gland'), ('pituitary', 'pituitary'), ('small_intestine', 'small_intestine'), ('esophagus', 'esophagus'), ('spleen', 'spleen'), ('stomach', 'stomach'), ('nerve', 'nerve'), ('lung', 'lung'), ('skin', 'skin'), ('breast', 'breast'), ('testis', 'testis'), ('adrenal_gland', 'adrenal_gland'), ('adipose_tissue', 'adipose_tissue'), ('brain', 'brain'), ('prostate', 'prostate'), ('ovary', 'ovary'), ('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('pancreas', 'pancreas'), ('kidney', 'kidney'), ('thyroid', 'thyroid'), ('heart', 'heart')], max_length=40),
        ),
    ]
