# Generated by Django 2.2 on 2019-09-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0021_auto_20190909_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('lung', 'lung'), ('pituitary', 'pituitary'), ('adrenal_gland', 'adrenal_gland'), ('liver', 'liver'), ('prostate', 'prostate'), ('vagina', 'vagina'), ('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('uterus', 'uterus'), ('small_intestine', 'small_intestine'), ('thyroid', 'thyroid'), ('testis', 'testis'), ('salivary_gland', 'salivary_gland'), ('spleen', 'spleen'), ('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('pancreas', 'pancreas'), ('stomach', 'stomach'), ('blood_vessel', 'blood_vessel'), ('kidney', 'kidney'), ('whole_blood', 'whole_blood'), ('ovary', 'ovary'), ('heart', 'heart'), ('skin', 'skin'), ('adipose_tissue', 'adipose_tissue'), ('nerve', 'nerve'), ('brain', 'brain'), ('colon', 'colon'), ('muscle', 'muscle'), ('esophagus', 'esophagus'), ('breast', 'breast')], max_length=40),
        ),
    ]
