# Generated by Django 2.2 on 2019-09-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0024_auto_20190909_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('spleen', 'spleen'), ('breast', 'breast'), ('uterus', 'uterus'), ('pancreas', 'pancreas'), ('whole_blood', 'whole_blood'), ('vagina', 'vagina'), ('stomach', 'stomach'), ('brain', 'brain'), ('prostate', 'prostate'), ('kidney', 'kidney'), ('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('ovary', 'ovary'), ('liver', 'liver'), ('small_intestine', 'small_intestine'), ('nerve', 'nerve'), ('pituitary', 'pituitary'), ('testis', 'testis'), ('heart', 'heart'), ('adrenal_gland', 'adrenal_gland'), ('muscle', 'muscle'), ('salivary_gland', 'salivary_gland'), ('blood_vessel', 'blood_vessel'), ('skin', 'skin'), ('thyroid', 'thyroid'), ('colon', 'colon'), ('lung', 'lung'), ('adipose_tissue', 'adipose_tissue'), ('esophagus', 'esophagus')], max_length=40),
        ),
    ]
