# Generated by Django 2.2 on 2019-09-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0029_auto_20190909_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpression',
            name='tissue_type',
            field=models.CharField(choices=[('uterus', 'uterus'), ('prostate', 'prostate'), ('thyroid', 'thyroid'), ('muscle', 'muscle'), ('pancreas', 'pancreas'), ('whole_blood', 'whole_blood'), ('kidney', 'kidney'), ('brain', 'brain'), ('vagina', 'vagina'), ('liver', 'liver'), ('pituitary', 'pituitary'), ('small_intestine', 'small_intestine'), ('ovary', 'ovary'), ('esophagus', 'esophagus'), ('skin', 'skin'), ('colon', 'colon'), ('testis', 'testis'), ('cells_-_ebv-transformed_lymphocytes', 'cells_-_ebv-transformed_lymphocytes'), ('cells_-_transformed_fibroblasts', 'cells_-_transformed_fibroblasts'), ('lung', 'lung'), ('adrenal_gland', 'adrenal_gland'), ('adipose_tissue', 'adipose_tissue'), ('spleen', 'spleen'), ('blood_vessel', 'blood_vessel'), ('breast', 'breast'), ('heart', 'heart'), ('salivary_gland', 'salivary_gland'), ('nerve', 'nerve'), ('stomach', 'stomach')], max_length=40),
        ),
    ]
