apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: es-master
  namespace: {{ NAMESPACE }}
  labels:
    component: elasticsearch
    role: master
spec:
  replicas: {{ ES_MASTER_NUM_PODS }}
  template:
    metadata:
      labels:
        name: es-master
        deployment: {{ DEPLOY_TO }}
        component: elasticsearch
        role: master
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-master
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: quay.io/pires/docker-elasticsearch-kubernetes:{{ ELASTICSEARCH_VERSION }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: "{{ ES_CLUSTER_NAME }}"
        - name: NUMBER_OF_MASTERS
          value: "{{ ES_MASTER_NUM_PODS }}"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: ES_JAVA_OPTS
          value: "-Xms2g -Xmx2g"
        - name: ES_PLUGINS_INSTALL
          value: "repository-gcs"  # ,mapper-size
        ports:
        - containerPort: 9300
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
