# Generated by Django 2.2 on 2019-09-09 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gene_lists', '0001_initial'),
        ('seqr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genelist',
            name='seqr_locus_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seqr.LocusList'),
        ),
    ]
